apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The namespace where all resources will be created.
namespace: llama-services

resources:
- pvc.yaml
# The crd-instance.yaml will be added here dynamically by the operator

# These labels will be applied to every resource.

replacements:
- source:
    group: llamastack.io
    kind: LlamaStackDistribution
    version: v1alpha1
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: PersistentVolumeClaim
- source:
    fieldPath: spec.server.storage.size
    group: llamastack.io
    kind: LlamaStackDistribution
    version: v1alpha1
  targets:
  - fieldPaths:
    - spec.resources.requests.storage
    select:
      kind: PersistentVolumeClaim
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: llama-stack-operator
    app.kubernetes.io/part-of: llama-stack
    some-other-label: some-value
