name: Run E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      # Add disk space monitoring throughout the workflow
      - name: Initial disk space check
        run: |
          echo "=== Initial Disk Space ==="
          df -h
          echo "=== Top 20 directories by size ==="
          du -h -d1 / 2>/dev/null | sort -hr | head -20

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.mod

      - name: Disk space after Go setup
        run: |
          echo "=== Disk Space After Go Setup ==="
          df -h

      - name: Install dependencies
        run: |
          go mod download
          make manifests generate fmt vet

      - name: Disk space after dependencies
        run: |
          echo "=== Disk Space After Dependencies ==="
          df -h

      - name: Build operator image
        run: |
          make image-build IMG=controller:e2e CONTAINER_TOOL=docker

      - name: Disk space after operator build
        run: |
          echo "=== Disk Space After Operator Build ==="
          df -h
          echo "=== Docker images ==="
          docker images

      - name: Create kind cluster
        run: |
          kind create cluster --name e2e-tests

      - name: Disk space after kind cluster
        run: |
          echo "=== Disk Space After Kind Cluster ==="
          df -h

      - name: Load operator image
        run: |
          kind load docker-image controller:e2e --name e2e-tests

      - name: Disk space after loading operator
        run: |
          echo "=== Disk Space After Loading Operator ==="
          df -h

      - name: Deploy operator
        run: |
          kubectl config use-context kind-e2e-tests
          make deploy IMG=controller:e2e

      - name: Disk space after deploying operator
        run: |
          echo "=== Disk Space After Deploying Operator ==="
          df -h

      - name: Wait for operator
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/llama-stack-k8s-operator-controller-manager -n llama-stack-k8s-operator-system

      - name: Monitor disk during e2e tests
        run: |
          # Start background disk monitor
          (while true; do
            echo "=== Disk Monitor at $(date) ==="
            df -h | grep -E "Filesystem|/dev/root"
            sleep 30
          done) &
          MONITOR_PID=$!
          echo "MONITOR_PID=$MONITOR_PID" >> $GITHUB_ENV

      - name: Run e2e tests
        run: |
          make test-e2e
        continue-on-error: true

      - name: Stop disk monitor and show final state
        if: always()
        run: |
          if [ ! -z "$MONITOR_PID" ]; then
            kill $MONITOR_PID || true
          fi
          echo "=== Final Disk Space ==="
          df -h
          echo "=== Top 20 directories by size ==="
          du -h -d1 / 2>/dev/null | sort -hr | head -20
          echo "=== Docker images ==="
          docker images
          echo "=== Kind cluster info ==="
          docker ps -a

      - name: Collect diagnostic data
        if: always()
        run: |
          # Set kubectl context for Kind cluster
          kubectl config use-context kind-e2e-tests
          # Collect logs and resource usage
          kubectl get all -A
          kubectl describe nodes
          kubectl top nodes || true
          kubectl top pods -A || true
